name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
      types: [checks_requested]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true
    - name: Install dependencies
      run: |
        uv sync --all-extras --dev
    - name: Pre-commit checks
      run: |
        uv run pre-commit run --all-files
    - name: Run tests
      run: |
        uv run pytest
    - name: Sphinx documentation build
      run: |
        make docs
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' && matrix.python-version == '3.13' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html/
        force_orphan: true
